version: '3.5'

services:
  main:
    build:
      context: .
      args:
        - WORDDIR=$PWD
    image: vul-main
    user: root
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
      internal:
      frp_containers:
      frp:
        ipv4_address: 10.1.0.2

  frps:
    image: vul-frp
#    build: ./frp
    restart: always
    volumes:
      - ./frp:/conf/
    expose:
      - 80
    entrypoint:
      - /app/frps
      - -c
      - /conf/frps.ini
    networks:
      frp:
        ipv4_address: 10.1.0.3

  frpc:
    image: vul-frp
#    build: ./frp
    restart: always
    volumes:
      - ./frp:/conf/
    expose:
      - 7400
    entrypoint:
      - /app/frpc
      - -c
      - /conf/frpc.ini
    networks:
      frp:
        ipv4_address: 10.1.0.4
      frp_containers:

networks:
  defualt:
  internal:
    internal: true
  frp:
    name: "vul_frp"
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
  frp_containers:
    name: "vul_frp_containers"
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16
